# Generated by Django 4.0.3 on 2022-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_champion_customuser_champions'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='hand',
            field=models.IntegerField(default=0),
        ),
    ]
