# Generated by Django 4.0.3 on 2022-03-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
