# Generated by Django 4.0.3 on 2022-03-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_champion_is_user_pc_is_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PC',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='is_user',
        ),
    ]
