# Generated by Django 4.0 on 2022-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0006_delete_pc_remove_champion_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='champions',
            field=models.ManyToManyField(blank=True, to='base.Champion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
