# Generated by Django 4.0 on 2022-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_champion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='category',
        ),
        migrations.AddField(
            model_name='champion',
            name='category',
            field=models.ManyToManyField(blank=True, to='base.Category', verbose_name='Category'),
        ),
    ]
