# Generated by Django 4.0.3 on 2022-03-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_champion_category_champion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
    ]
