# Generated by Django 4.0 on 2022-03-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_customuser_description_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matches',
            field=models.IntegerField(default=0, verbose_name='マッチ数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='防衛数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wins_rate',
            field=models.IntegerField(default=0, verbose_name='勝率'),
        ),
    ]
