# Generated by Django 4.0 on 2022-03-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_customuser_matches_customuser_wins_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
