# Generated by Django 4.0 on 2022-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_customuser_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='img_url',
        ),
        migrations.AddField(
            model_name='champion',
            name='picture',
            field=models.FileField(null=True, upload_to='character/'),
        ),
    ]
