# Generated by Django 4.0 on 2022-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_champion_img_url_champion_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(null=True, upload_to='', verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='champion',
            name='picture',
            field=models.FileField(upload_to='character/'),
        ),
    ]
