# Generated by Django 4.0 on 2022-03-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_enemy_alter_champion_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='picture',
            field=models.FileField(null=True, upload_to='enemy/', verbose_name='image'),
        ),
    ]
