# Generated by Django 4.0 on 2022-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_enemy_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donations',
            field=models.FloatField(default=0, verbose_name='寄付額'),
        ),
    ]
